Repository PrefectHQ/prometheus-prefect-exporter, pull requests merged in 2024-05, with the labels that each got.

#23 General housekeeping updates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/dependabot.yaml
  .github/release.yaml
  .github/workflows/release-build-deploy.yaml
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  CODEOWNERS
  CONTRIBUTING.md
  Dockerfile
  LICENSE
  MAINTAINERS.md
  Pipfile
  Pipfile.lock
  README.md
  main.py
  package.json
  requirements.txt
Labels: enhancement

#18 feat(dashboards): add workers
  dashboards/prefect-platform-overview.json
Labels: feature

#27 chore: precommit run
  .dockerignore
  .pre-commit-config.yaml
  dashboards/prefect-flow-run-overview.json
  metrics/deployments.py
  metrics/flow_runs.py
  metrics/flows.py
  metrics/healthz.py
  metrics/metrics.py
  metrics/work_pools.py
  metrics/work_queues.py
Labels: maintenance

#28 chore: remove slim from python image for rust compilier
  Dockerfile
Labels: fix

#29 chore: remove uv (for now)
  Dockerfile
Labels: fix

#31 chore: fix spelling of `Initializing`
  main.py
Labels: fix
